In [2]:
import numpy as np
a=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
a.ndim

2

In [5]:
a.shape

(3, 3)

In [6]:
a.size

9

In [7]:
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

In [12]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]],dtype=np.float32)# int to float

In [10]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [11]:
type(a)

numpy.ndarray

In [21]:
np.zeros((3,4),dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [25]:
np.ones((5,4),dtype=np.complex)

C:\Users\Ramakrishna\AppData\Local\Temp\ipykernel_2628\2324001063.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((5,4),dtype=np.complex)


array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [31]:
a=np.eye(5)

In [29]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a.dtype

dtype('float64')

In [33]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
z=np.arange(11)

In [36]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.char.array(["Thiru","PK","uday","Sur","rashmi"])

chararray(['Thiru', 'PK', 'uday', 'Sur', 'rashmi'], dtype='<U6')

In [42]:
np.char.add(["CSK","mi","Gl"],["SRH","JK","Hyd"])

array(['CSKSRH', 'miJK', 'GlHyd'], dtype='<U6')

In [43]:
np.char.multiply("hello",3)

array('hellohellohello', dtype='<U15')

In [50]:
np.char.center("Helloworld",30,fillchar="-")

array('----------Helloworld----------', dtype='<U30')

In [54]:
np.char.center("king will kill the witch",40,fillchar="^")

array('^^^^^^^^king will kill the witch^^^^^^^^', dtype='<U40')

In [55]:
np.char.title("Hello world")

array('Hello World', dtype='<U11')

In [56]:
np.char.upper("hello")

array('HELLO', dtype='<U5')

In [57]:
np.char.lower("HELLO KING I AM KILLING U SOON")

array('hello king i am killing u soon', dtype='<U30')

In [58]:
np.char.split("Hi How are you i am under the water")

array(list(['Hi', 'How', 'are', 'you', 'i', 'am', 'under', 'the', 'water']),
      dtype=object)

In [60]:
np.char.capitalize("where you now i am waiting for you")

array('Where you now i am waiting for you', dtype='<U34')

In [65]:
np.char.strip(["what","How","King","Low"])

array(['what', 'How', 'King', 'Low'], dtype='<U4')

In [67]:
np.char.join(["hel"],["--","**"])

array(['-hel-', '*hel*'], dtype='<U5')

In [70]:
np.char.replace("Myy Name is king","king","queen")

array('Myy Name is queen', dtype='<U17')

# pandas 

In [73]:
import pandas as pd

In [76]:
print(pd.__version__)

1.4.4


In [80]:
a=np.arange(5)
ser=pd.Series(a)

In [85]:
b=np.array([1,2,3,4,5])
s=pd.Series(b,index=[1,2,3,4,5])

In [86]:
s

1    1
2    2
3    3
4    4
5    5
dtype: int32

In [96]:
c=[[1,2,3,4],[5,6,7,8],[9,3,1,1]]

In [97]:
s1=pd.Series(c)

In [99]:
s1.index=['A','B','C']

In [101]:
s1

A    [1, 2, 3, 4]
B    [5, 6, 7, 8]
C    [9, 3, 1, 1]
dtype: object

In [117]:
ran=np.random.rand(5)
s3=pd.Series(ran)

In [118]:
ran

array([0.5142846 , 0.04584169, 0.7378472 , 0.06521322, 0.39018337])

In [119]:
s3=pd.Series(ran)

In [120]:
s3.index=['A','B','C','D','F']

In [121]:
s3

A    0.514285
B    0.045842
C    0.737847
D    0.065213
F    0.390183
dtype: float64

In [125]:
d={"A":np.random.rand(3),"B":np.random.rand(3)}

In [126]:
s5=pd.Series(d)

In [127]:
s5

A    [0.8592472230868896, 0.09638600411944098, 0.02...
B    [0.6091822150956464, 0.4882536965024874, 0.103...
dtype: object

In [132]:
df=pd.concat([s5,s3],axis=1)

In [135]:
df.columns=['A','B']

In [136]:
df

A         B
A  [0.8592472230868896, 0.09638600411944098, 0.02...  0.514285
B  [0.6091822150956464, 0.4882536965024874, 0.103...  0.045842
C                                                NaN  0.737847
D                                                NaN  0.065213
F                                                NaN  0.390183

In [137]:
s6=s5.append(s3)

C:\Users\Ramakrishna\AppData\Local\Temp\ipykernel_2628\599356529.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s6=s5.append(s3)


In [138]:
s6

A    [0.8592472230868896, 0.09638600411944098, 0.02...
B    [0.6091822150956464, 0.4882536965024874, 0.103...
A                                             0.514285
B                                             0.045842
C                                             0.737847
D                                             0.065213
F                                             0.390183
dtype: object

In [139]:
s7=pd.concat([s6,s5])

In [140]:
s7

A    [0.8592472230868896, 0.09638600411944098, 0.02...
B    [0.6091822150956464, 0.4882536965024874, 0.103...
A                                             0.514285
B                                             0.045842
C                                             0.737847
D                                             0.065213
F                                             0.390183
A    [0.8592472230868896, 0.09638600411944098, 0.02...
B    [0.6091822150956464, 0.4882536965024874, 0.103...
dtype: object

In [144]:
s7.drop("B",inplace=True)

In [145]:
s7

A    [0.8592472230868896, 0.09638600411944098, 0.02...
A                                             0.514285
C                                             0.737847
D                                             0.065213
F                                             0.390183
A    [0.8592472230868896, 0.09638600411944098, 0.02...
dtype: object

In [ ]:
date=pd.date_range("today",per)